name: smart2fa # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Open source software for 2fa authorization # 79 char long summary
description: Smart2FA is a free, secure, open-source app allows you protect your accounts by adding 2-factor authentication (2FA). The app brings together best-in-class security practices and a seamless user experience together. Enable Smart2FA for your favorite online services.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
